name: ketabkhan_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # iOS-style icons
  cupertino_icons: ^1.0.8

  # Networking
  dio: ^5.7.0

  # State management
  flutter_riverpod: ^2.5.1

  # Routing
  go_router: ^14.2.7

  # Secure token storage
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.3
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
